---
title: "Chicago Domestic Crimes During Pandemic"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=F, warning=F)
domvio <- read.csv("chicago.csv")
library(tidyverse)
```


```{r mutate data to make month day year}
domvio<-domvio %>%
  mutate(MONTH = as.integer(substring(DATE..OF.OCCURRENCE, 0, 2))) %>% 
  mutate(DAY = as.integer(substring(DATE..OF.OCCURRENCE, 4,5))) %>% 
  mutate(YEAR = as.integer(substring(DATE..OF.OCCURRENCE, 7,10)))

#heres what the data looks like
glimpse(domvio)
```


```{r making indicators}
domvio_mut<-domvio

#create an indicator for being before covid entirely
#this indicator is "isbeforecovid"

domvio_mut<-domvio_mut %>%
  mutate(isbeforecovid = case_when(
    YEAR == 2019 ~ 1,
    YEAR == 2020 & MONTH == 1 & DAY <=24 ~ 1,
    YEAR == 2020 & MONTH == 1 & DAY > 24 ~ 0,
    YEAR == 2020 & MONTH > 1 ~ 0,
    ))

#create an indicator for being before lockdown (tho covid is in the USA)
#this indicator is "isprelockdown"
domvio_mut<-domvio_mut %>%
  mutate(isprelockdown = case_when(
    YEAR == 2019 ~ 0,
    YEAR == 2020 & MONTH == 1 & DAY <=24 ~ 0,
    YEAR == 2020 & MONTH == 1 & DAY > 24 ~ 1,
    YEAR == 2020 & MONTH == 2  ~ 1, 
    YEAR == 2020 & MONTH == 3 & DAY < 22 ~ 1,
    YEAR == 2020 & MONTH == 3 & DAY >= 22 ~ 0,
    YEAR == 2020 & MONTH > 3 ~ 0
    ))

#create an indicator for being in the lockdown
#this indicator is "islockdown"
domvio_mut<-domvio_mut %>%
  mutate(islockdown = case_when(
    YEAR == 2019 ~ 0,
    YEAR == 2020 & MONTH < 3 ~ 0, 
    YEAR == 2020 & MONTH == 3 & DAY < 22 ~ 0,
    YEAR == 2020 & MONTH == 3 & DAY >= 22 ~ 1,
    YEAR == 2020 & MONTH == 4 ~ 1,
    YEAR == 2020 & MONTH >= 5 ~ 0
    ))

#create an indicator for phase 2 in the recovery
#this indicator is "isphase2"
domvio_mut<-domvio_mut %>%
  mutate(isrecovery = case_when(
    YEAR == 2019 ~ 0,
    YEAR == 2020 & MONTH < 5 ~ 0, 
    YEAR == 2020 & MONTH == 5 ~ 1,
    YEAR == 2020 & MONTH == 6 & DAY < 3 ~ 1,
    YEAR == 2020 & MONTH == 6 & DAY >= 3 ~ 0,
    YEAR == 2020 & MONTH >= 7 ~ 0
    ))

#create an indicator for phase 3 in the recovery
#this indicator is "isphase3"
domvio_mut<-domvio_mut %>%
  mutate(isphase3 = case_when(
    YEAR == 2019 ~ 0,
    YEAR == 2020 & MONTH < 6 ~ 0, 
    YEAR == 2020 & MONTH == 6 & DAY >= 3 & DAY <= 25 ~ 1,
    YEAR == 2020 & MONTH == 6 & DAY > 25 ~ 0,
    YEAR == 2020 & MONTH >= 7 ~ 0
    ))

#create an indicator for phase 4 in the recovery
#this indicator is "isphase4"
domvio_mut<-domvio_mut %>%
  mutate(isphase4 = case_when(
    YEAR == 2019 ~ 0,
    YEAR == 2020 & MONTH < 6 ~ 0, 
    YEAR == 2020 & MONTH == 6 & DAY < 26 ~ 0,
    YEAR == 2020 & MONTH == 6 & DAY >= 26 ~ 1,
    YEAR == 2020 & MONTH >= 7 ~ 1
    ))
  
#create an indicator for cases of dom violence
#this indicator is "isdomviolence"
domvio_mut<-domvio_mut %>%
  mutate(isdomviolence = case_when(
    SECONDARY.DESCRIPTION == "VIOLATION OF BAIL BOND - DOMESTIC VIOLENCE" |
    SECONDARY.DESCRIPTION == "DOMESTIC BATTERY SIMPLE" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY: OTHER DANGEROUS WEAPON" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY: KNIFE / CUTTING INSTSTRUMENT" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY: HANDS/FIST/FEET SERIOUS INJURY" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY: HANDGUN" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY - OTHER FIREARM" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT" |
    SECONDARY.DESCRIPTION == "AGGRAVATED DOMESTIC BATTERY - HANDGUN" |
    SECONDARY.DESCRIPTION == "AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY" ~ 1,
    SECONDARY.DESCRIPTION != "VIOLATION OF BAIL BOND - DOMESTIC VIOLENCE" &
    SECONDARY.DESCRIPTION != "DOMESTIC BATTERY SIMPLE" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY: OTHER DANGEROUS WEAPON" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY: KNIFE / CUTTING INSTSTRUMENT" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY: HANDS/FIST/FEET SERIOUS INJURY" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY: HANDGUN" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY - OTHER FIREARM" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT" &
    SECONDARY.DESCRIPTION != "AGGRAVATED DOMESTIC BATTERY - HANDGUN" &
    SECONDARY.DESCRIPTION != "AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY" ~ 0
    ))
```

```{r lookning at some data pointsss}
#if you are wondering about how the actual data looks like there it is
#number of observations during lockdown
domvio_mut %>% 
  count (islockdown)

#number of observations during recovery
domvio_mut %>% 
  count (isrecovery)

#number of observations during p3, p4
domvio_mut %>% 
  count (isphase3)
domvio_mut %>% 
  count(isphase4)

#number of observations during in 2020 pre covid
domvio_mut %>% 
  count (isbeforecovid)


#number of cases of domestic violence
domvio_mut %>% 
  count(isdomviolence)

#see number of cases of domestic violence on a given day
domvio_mut %>% 
  filter(YEAR=="2020") %>% 
  filter(MONTH=="05") %>% 
  filter(DAY=="30") %>% 
  count(isdomviolence)

#observations of dom violence on a day or month
domvio_mut %>% 
  filter(YEAR=="2019") %>% 
  filter(MONTH=="07") %>%
  count(isdomviolence)
```
```{r check}
domvio_cat<-domvio_mut %>%
  group_by(SECONDARY.DESCRIPTION) %>%
  summarise(n=n())
domvio_cat
```

```{r creating this indicator that shows before covid, during lockdown, and phase 3 together}
domvio_mut<-domvio_mut %>% 
  mutate(chisquare_indicators= case_when(isbeforecovid == 1 ~ "pre",
                                         isprelockdown == 1 ~ "pre",
                                         islockdown == 1 ~ "lockdown",
                                         isrecovery == 1 ~ "lockdown",
                                         isphase3 == 1 ~ "post",
                                         isphase4 == 1 ~ "post"
                                         ) )
domvio_mut
```

```{r chisquared test}
table(domvio_mut$isdomviolence, domvio_mut$chisquare_indicators)
chisq.test(table(domvio_mut$isdomviolence, domvio_mut$chisquare_indicators))


```